
package localhost.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExampleService", targetNamespace = "http://localhost/example.wsdl", wsdlLocation = "http://127.0.0.1/Example?wsdl")
public class ExampleService
    extends Service
{

    private final static URL EXAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXAMPLESERVICE_EXCEPTION;
    private final static QName EXAMPLESERVICE_QNAME = new QName("http://localhost/example.wsdl", "ExampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/Example?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMPLESERVICE_WSDL_LOCATION = url;
        EXAMPLESERVICE_EXCEPTION = e;
    }

    public ExampleService() {
        super(__getWsdlLocation(), EXAMPLESERVICE_QNAME);
    }

    public ExampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMPLESERVICE_QNAME, features);
    }

    public ExampleService(URL wsdlLocation) {
        super(wsdlLocation, EXAMPLESERVICE_QNAME);
    }

    public ExampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMPLESERVICE_QNAME, features);
    }

    public ExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringPort
     */
    @WebEndpoint(name = "ExamplePort")
    public StringPort getExamplePort() {
        return super.getPort(new QName("http://localhost/example.wsdl", "ExamplePort"), StringPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringPort
     */
    @WebEndpoint(name = "ExamplePort")
    public StringPort getExamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/example.wsdl", "ExamplePort"), StringPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMPLESERVICE_EXCEPTION!= null) {
            throw EXAMPLESERVICE_EXCEPTION;
        }
        return EXAMPLESERVICE_WSDL_LOCATION;
    }

}
