
package localhost.example;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "stringPort", targetNamespace = "http://localhost/example.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StringPort {


    /**
     * 
     * @param input
     */
    @WebMethod(action = "stringPass")
    @Oneway
    public void stringPass(
        @WebParam(name = "input", partName = "input")
        String input);

}
